### ISSUE TITLE
db not creating - Similar to Blueprint 404 issue

### ISSUE THREAD

**Issue by mathieum906** [talkpython/data-driven-web-apps-with-flask#10]
Hello! Similar to the previously-noted Blueprint 404 issue which was corrected with:

`register_blueprints()`
`if __name__ == '__main__':
    main()`

I'm now seeing an issue with the db not creating because setup_db is not being accessed. I moved setup_db here:

`register_blueprints()`
`setup_db()`
`if __name__ == '__main__':
    main()`

... and still nothing, but at least it prints out the connection string. Any ideas for how to solve this?

**Comment by mathieum906** [comment]
As a note, this is being run within PyCharm. I believe the app is starting BEFORE the db call, and I'm not sure how to solve that. 
![image](https://user-images.githubusercontent.com/30209192/66731725-13036380-ee59-11e9-8d07-4fdecce13fd5.png)

**Comment by mathieum906** [comment]
Did a bit more research and found that my app is stuck on 
`engine = sa.create_engine(conn_str, echo=False)`
and does not progress to the next line. I can't find an answer to this anywhere... 😞

**Comment by mathieum906** [comment]
Finally figured this out. Had to download the Win64 version of sqlite3.dll and put it in the DLL directory of my main Python install. What a hassle.

**Comment by mikeckennedy** [comment]
Hi @mathieum906 Wow! I would have never guessed! Crazy. Is it possible that you have the 32-bit rather than 64-bit version of Python?

**Comment by mathieum906** [comment]
I have 64bit python running. 

The frustrating thing is that when I installed Alembic, the issue happened again, which I really don't understand... the DLL exists and is in the right place, and yet Alembic can't find it.

**Comment by mathieum906** [comment]
Works when I run it from Anaconda Prompt, but not from PyCharm... I think at some point I need to wipe out my Python installation and install it without Anaconda...?

**Comment by mikeckennedy** [comment]
Yeah, possibly. You could try typing C:> `where python` and see what it says for the paths. Could just be changing an order in your path settings on your account.
