### ISSUE TITLE
Small error in order of lines in code:  Chapter 10 - basic_inserts.py

### ISSUE THREAD

**Issue by aambrioso1** [talkpython/data-driven-web-apps-with-flask#14]
There is a small error in basic_inserts.py.   It probably went unnoticed because it only affects folks that are not using Pycharm.   Here's the problem:

import pypi_org.data.db_session as db_session
from pypi_org.data.package import Package
from pypi_org.data.releases import Release
 
# Make it run more easily outside of PyCharm
sys.path.insert(0, os.path.abspath(os.path.join(
     os.path.dirname(__file__), "..", "..")))

The code to fix the problem with the system path needs to be place before the imports.

Thanks for the course.    I am slogging along steadily.

Cheers!
Alex in Valrico, Florida

PS:  Still not haven't worked out how to do pull requests.

**Comment by mikeckennedy** [comment]
Hi! Thanks for this. I think it's already there, right:

https://github.com/talkpython/data-driven-web-apps-with-flask/blob/b98d93fd01f63187b6099ea17700243be332b09e/app/ch10_using_sqlachemy/final/pypi_org/bin/basic_inserts.py#L8

Let me know if I'm missing it. :)

As for PRs, just fork the repo (make sure it's in sync: see steps 5 & 6, then git pull: https://www.dataschool.io/how-to-contribute-on-github/ ), make the change in your repo, push it to github. Visit github's page for your repo, it'll have a create PR green button, press that!

**Comment by aambrioso1** [comment]
Hi Michael,

Thanks for the quick response.   The problem with the code is that it's out
of order.   The path-fix code comes after the import call so the program
crashes (for me using Sublime with Windows).    I do not know git and
GItHub well yet.   I am working on it.    I will look at doing a pull
request.  Looks straightforward.   So much to learn....

-Alex
