### ISSUE TITLE
Ch 10, Video 7 - Inserting the real Pypi data - where's the load_data.py file?

### ISSUE THREAD

**Issue by exfrog** [talkpython/data-driven-web-apps-with-flask#17]
the video starts saying we aren't going to write the load_data.py file, but it does not mention where to find it to bring it in to the project
Copying the load_data.py file from the final folder and trying to run it along with this video gives the error:

Traceback (most recent call last):
  File "C:/PyWorkspace/data-driven-web-apps-with-flask/app/ch10_using_sqlachemy/starter/pypi_org/bin/load_data.py", line 16, in <module>
    from pypi_org.infrastructure.num_convert import try_int
ModuleNotFoundError: No module named 'pypi_org.infrastructure.num_convert'

is there a different load_data.py file we should use here?

**Comment by jfcorreas** [comment]
Hi, you must add the file **_num_convert.py_** to your project. You can find the file here: 
https://github.com/talkpython/data-driven-web-apps-with-flask/tree/master/app/ch10_using_sqlachemy/final/pypi_org/infrastructure

**Comment by mikeckennedy** [comment]
Hi @exfrog sorry for the confusion. I think I copied it in during the video but I don't recall 100% so I just added it to the starter project here. @jfcorreas Thank you for helping in the meantime!

**Comment by mikeckennedy** [comment]
See commit: https://github.com/talkpython/data-driven-web-apps-with-flask/commit/5346e7cc13852be42d827c2d240fefc9217995ef
