### ISSUE TITLE
Able to manually enter hhtp://.../account/login in the address bar when a user is already logged in.

### ISSUE THREAD

**Issue by BigMoonTech** [talkpython/data-driven-web-apps-with-flask#24]
If a user is already logged in, they can manually go to the login page even after they are already logged in. Instead, manually going to the login page if logged in should redirect to the account page.

**Comment by mikeckennedy** [comment]
Hey @BigMoonTech Thanks for pointing this out. I did miss it during the recording. But you are right that this is the correct behavior. See the associated commit above. It should be fixed now.
