### ISSUE TITLE
Update certbot https instructions

### ISSUE THREAD

**Issue by jdilger** [talkpython/data-driven-web-apps-with-flask#26]
Hey there,

I ran into an issue with the SSL certbot install when revisiting this tutorial for another project I am doing (so I am not following the lesson to the tee here... and maybe the issue is just me 😁 ). The PPA install has been deprecated
```
# add-apt-repository ppa:certbot/certbot

PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/certbot/certbot/ubuntu/ kinetic main'
Description:
The PPA has been DEPRECATED.
```

Following the [instructions from certbot](https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal) worked for me on Ubuntu 22.1

```
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
```

**Comment by mikeckennedy** [comment]
Thanks @jdilger You're thinking of updating the video instructions / steps (at least minimally) or did you have some instructions I put somewhere (e.g. like the server setup script steps)?

**Comment by jdilger** [comment]
Hey @mikeckennedy, yes, the certbot instructions for the `server_setup.sh` have been deprecated. The specific lines these effects are:

https://github.com/talkpython/data-driven-web-apps-with-flask/blob/0d4e4d72be982f7e5050ee1a7293dbe4ade40ba6/app/ch15_deploy/final/server/server_setup.sh#L80-L82

I was following that portion for a personal project so I haven't tested it against this repo. If you like I can make a PR for you to review but it would need some minor editing in the course video to reflect the changes.

**Comment by mikeckennedy** [comment]
Hi @jdilger 

Thanks so much for following up on this. It took awhile for me to be able to work on it. There are 5 courses that needed their code updated and their videos fixed. I did that for them, including the video you pointed out:

https://training.talkpython.fm/player/course/building-data-driven-web-applications-in-python-with-flask-sqlalchemy-and-bootstrap/lecture/201510

As well as the server_setup.sh files included with all those course downloads.

I appreciate your helping raise the awareness on this.
