### ISSUE TITLE
Chapter 07

### ISSUE THREAD

**Issue by cmcknight** [talkpython/data-driven-web-apps-with-flask#3]
When the Login button is clicked with empty fields the video shows that password field turns red. This does occur when using Firefox but it does not occur when using Safari on the Mac.

Not a bug per se, but something that may confuse users.

**Comment by mikeckennedy** [comment]
Hi @cmcknight Thanks for the heads up. This is one of the joys of the web. Each browser manufacturer chooses what a failed validation looks like and the messages and even what counts as valid.
